name: Upload sarif report

on:
  push:
    main:

jobs:
  upload-sarif:
    runs-on: ubuntu-latest
    steps:
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif