name: 

on:
  push:
    main:

permissions:
  id-token: write # for assuming aws iam role (to publish to s3)
  contents: write # for publishing to github releases

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif